### ISSUE TITLE
presence of NAs in the data

### ISSUE THREAD

**Issue by desval** [atahk/pscl#4]
Hi,

firstly, thanks for developing this package!

When computing, for instance, the McFadden pseudo R2, the log likelihood of the null model does not take in account that the full model might have been estimated using less observations, because of missing data. This is not a big issue, but I bet there will be other people out there that have unknowingly  reported the wrong pR2 because of this.

I was wondering if this is a design choice.
Thanks!

**Comment by atahk** [comment]
Thanks for catching this bug! I just pushed a commit that fixes it (and also extends `pR2` to work with many other types of fitted models). It'll make its way onto CRAN whenever the next version is released. In the meantime, you can get the fixed version by installing the package from github using the devtools package (i.e., `devtools::install_github("atahk/pscl")`).
